version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
         - BUNDLER_VERSION: '1.16.6'
         - RAILS_ENV: 'development'
      - image: circleci/mysql:5.7
        environment:
         - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
         - MYSQL_DATABASE: chells-kitchen_development

     working_directory: ~/repo

     steps:
      - checkout
      - restore_cache
          name: bundle installの結果をリストア
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock"}}
            - v1-dependencies-
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: context設定の環境変数
          command: |
            echo "#{CHELLS-KITCHEN_DB_HOST}"
            echo "#{CHELLS-KITCHEN_DB_USER}"
            echo "#{CHELLS-KITCHEN_DB_PASSWORD}"
      - save_cache:
          name: bundle installの結果をキャッシュ
          paths: ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          commant: yarn
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://192.168.33.11:3306 -timeout 1m
      - run:
          name: Rspec実行
          command: bundle exec rspec
      - run:
          name: Rubocop実行
